CateBase/Controllers/BuyNowController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using BasePackageModule2.Data;
using BasePackageModule2.Helpers;
using BasePackageModule2.Models;
using InstaSharp;
using InstaSharp.Exceptions;
using InstaSharp.Interface;
using InstaSharp.Model;
using InstaSharp.Response;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Order = BasePackageModule2.Models.Order;

namespace BasePackageModule1.Controllers
{
    [Authorize]
    public class BuyNowController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        private IInstaMojoConfiguration _instaMojo;
        public BuyNowController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IInstaMojoConfiguration instaMojo)
        {
            _context = context;
            _userManager = userManager;
            _instaMojo = instaMojo;
        }

        public async Task<IActionResult> Index(int productId, int qty)
        {
            if (productId == 0 || qty == 0)
            {
                return BadRequest();
            }

            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);

            var addresses = await _context.Addresses.Where(u => u.UserId == user.Id).ToListAsync();
            ViewData["productId"] = productId;
            ViewData["qty"] = qty;

            ViewData["Addresses"] = addresses;

            return View();
        }
        public IActionResult ThankYou()
        {
            return View();
        }
        public async Task<IActionResult> Address(Address address, int productId, int qty)
        {
            if (!ModelState.IsValid)
            {
                ViewData["productId"] = productId;
                ViewData["qty"] = qty;

                return View(nameof(Index), address);
            }
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            address.UserId = user.Id;
            _context.Add(address);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(PaymentOptions), new { addressId = address.Id, productId, qty});
        }

        public async Task<IActionResult> CheckOutOptions(int productId, int qty)
        {
            if (productId == 0 || qty == 0)
            {
                return BadRequest();
            }

            var cOptions = new ACheckoutoptions
            {
                ProductId = productId,
                Qty = qty
            };

            var product = await _context.Products.FindAsync(productId);
            if (product == null)
            {
                return NotFound();
            }
            var subtotal = (double)(product.FinalPrice* qty);

            ViewData["Items"] = subtotal;

            return View(cOptions);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CheckOutOptions(string PaymentMode, int productId, int qty)
        {
            if (productId == 0 || qty == 0)
            {
                return BadRequest();
            }
            double subtotal = 0;

            var product = await _context.Products.FindAsync(productId);
            subtotal = (double)(product.FinalPrice * qty);

            ViewData["Items"] = subtotal;


            if (PaymentMode == null)
            {
                ModelState.AddModelError("PaymentMode", "Please Select Payment Mode.");
                var cOptions = new ACheckoutoptions
                {
                    ProductId = productId,
                    Qty = qty
                };

                return View(cOptions);
            }

            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);



         


            if (PaymentMode == "payOnline")
            {
                string instaEndpoint = InstamojoConstants.INSTAMOJO_API_ENDPOINT, instaAuthEndpoint = InstamojoConstants.INSTAMOJO_AUTH_ENDPOINT;


                if (_instaMojo.ClientId.Contains("test") || _instaMojo.ClientSecret.Contains("test"))
                {
                    instaEndpoint = InstamojoConstants.INSTAMOJO_API_ENDPOINT;
                    instaAuthEndpoint = InstamojoConstants.INSTAMOJO_AUTH_ENDPOINT;
                }

                else
                {
                    instaEndpoint = "https://api.instamojo.com/v2/";
                    instaAuthEndpoint = "https://www.instamojo.com/oauth2/token/";
                }

                IInstamojo objClass;
                try
                {
                    objClass = InstamojoImplementation.getApi(
                        _instaMojo.ClientId,
                        _instaMojo.ClientSecret,
                        instaEndpoint,
                        instaAuthEndpoint);
                }
                catch (Exception e)
                {
                    return Content("Something went wrong, Please try again after sometime");
                }




                try
                {
                    var transactionId = Guid.NewGuid().ToString();

                    #region   1. Create Payment Order
                    //  Create Payment Order
                    var objPaymentRequest = new PaymentOrder
                    {
                        name = $"{user.FirstName} {user.LastName}",
                        email = user.Email,
                        phone = user.PhoneNumber.Replace("+",""),
                        amount = subtotal,
                        currency = "INR",
                        description = "",
                        webhook_url = "https://poojacraft.in/Checkout/WebHook",
                        //webhook_url =   Url.Action("WebHook", "Checkout", null, protocol: "https"),
                        transaction_id = transactionId,
                        redirect_url = Url.Action("ProcessPayment", "Checkout", null, protocol: "https")
                    };
                    //Required POST parameters
                    //Extra POST parameters 

                    if (objPaymentRequest.validate())
                    {

                        if (objPaymentRequest.emailInvalid)
                        {
                            return Content("Email is not valid");
                        }
                        if (objPaymentRequest.nameInvalid)
                        {
                            return Content("Name is not valid");
                        }
                        if (objPaymentRequest.phoneInvalid)
                        {
                            return Content("Phone is not valid");
                        }
                        if (objPaymentRequest.amountInvalid)
                        {
                            return Content("Amount is not valid");
                        }
                        if (objPaymentRequest.currencyInvalid)
                        {
                            return Content("Currency is not valid");
                        }
                        if (objPaymentRequest.transactionIdInvalid)
                        {
                            return Content("Transaction Id is not valid");
                        }
                        if (objPaymentRequest.redirectUrlInvalid)
                        {
                            return Content("Redirect Url Id is not valid");
                        }
                        if (objPaymentRequest.webhookUrlInvalid)
                        {
                            return Content("Webhook URL is not valid");
                        }

                    }
                    else
                    {
                        try
                        {
                            var order = new Order
                            {
                                UserId = user.Id,
                                PaymentStatus = "Pending",
                                TransactionId = transactionId,
                                Amount = subtotal,
                            };
                            _context.Add(order);
                            await _context.SaveChangesAsync();

                            OrderProduct orderProduct = new OrderProduct
                            {
                                ProductId = product.Id,
                                OrderId = order.Id,
                                Quantity = qty
                            };
                            _context.Add(orderProduct);

                            await _context.SaveChangesAsync();

                            CreatePaymentOrderResponse objPaymentResponse = objClass.CreateNewPaymentRequest(objPaymentRequest);
                            return Redirect(objPaymentResponse.payment_options.payment_url);

                        }

                        catch (ArgumentNullException ex)
                        {
                            throw ex;
                        }
                        catch (WebException ex)
                        {
                            throw ex;
                        }
                        catch (IOException ex)
                        {
                            throw ex;
                        }
                        catch (InvalidPaymentOrderException ex)
                        {
                            throw ex;
                        }
                        catch (ConnectionException ex)
                        {
                            throw ex;
                        }
                        catch (BaseException ex)
                        {
                            throw ex;
                        }
                        catch (Exception ex)
                        {

CateBase/Views/BuyNow/CheckOutOptions.cshtml
@model BasePackageModule1.Controllers.BuyNowController.ACheckoutoptions

<div class="container">
    <div class="row mt-5 mb-5">
        <div class="col-md-6 offset-md-2">
            <h4>Checkout Option</h4>
            <form asp-action="CheckOutOptions" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <input type="hidden" asp-for="ProductId"/>
                <input type="hidden" asp-for="Qty"/>
                <div class="form-group form-check mt-2 mb-2">
                    <label class="form-check-label">
                        <input id="payOnline" value="payOnline" type="radio" asp-for="PaymentMode" class="form-check-input"> Pay Online
                    </label>
                </div>

                <div class="form-group form-check mt-2 mb-2">
                    <label class="form-check-label">
                        <input id="payAtShop" value="payAtShop" type="radio" asp-for="PaymentMode" class="form-check-input"> Pay at Shop
                    </label>
                </div>
                <button type="submit" class=" btn btn-primary btn-block">Confirm Order</button>
            </form>
        </div>
        
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title text-center text-primary">Order Summary</h5>
                    <hr />
                    <ul class="order-summary">
                        <li>Items:	  <span class="float-right">₹ @ViewBag.Items</span></li>
                        <li> Delivery:<span class="float-right">₹ 00</span></li>
                        <li>Total:	   <span class="float-right">₹ @ViewBag.Items</span></li>
                        <li>Promotion Applied:	-  <span class="float-right">₹ 00</span></li>
                        <hr />
                        <li><h5 class="text-primary">Order Total:<span class="float-right">₹ @ViewBag.Items</span></h5></li>
                    </ul>

                </div>
            </div>

        </div>

    </div>
</div>

CateBase/Views/BuyNow/Index.cshtml
@model Address

@{
    ViewData["Title"] = "Checkout";
}


<section id="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <h1 class="text-center text-white text-uppercase">Delivery Address</h1>
            </div>
        </div>

    </div>
</section>

<div class="container my-5">
    <div class="row">

        @foreach (var item in ViewBag.Addresses)
        {
            <div class="col-md-6 mb-2 mb-2">
                <div style="border: solid 1px gray; padding: 20px">
                    <h3>@item.Name @item.MobileNumber</h3>
                    <p>@item.MainAddress @item.City @item.State - @item.PinCode</p>

                    <a class="btn btn-primary button" asp-controller="BuyNow" asp-action="PaymentOptions" asp-route-addressId="@item.Id" asp-route-productId="@ViewBag.productId" asp-route-qty="@ViewBag.qty">Deliver to this Address</a>

                    <br />
                    <a href="/Identity/Account/Manage/EditAddress/@item.Id" class="btn text-success">Edit</a>

                </div>
            </div>
        }
    </div>
    <div class="row mt-4 mb-4">
        <div class="col-md-6">
            <h2 class="text-center main-title">Add a new address</h2>
            <form asp-action="Address">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" name="productId" value="@ViewBag.productId" />
                <input type="hidden" name="qty" value="@ViewBag.qty" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MobileNumber" class="control-label"></label>
                    <input asp-for="MobileNumber" class="form-control" />
                    <span asp-validation-for="MobileNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PinCode" class="control-label"></label>
                    <input asp-for="PinCode" class="form-control" />
                    <span asp-validation-for="PinCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Locality" class="control-label"></label>
                    <input asp-for="Locality" class="form-control" />
                    <span asp-validation-for="Locality" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MainAddress" class="control-label"></label>
                    <input asp-for="MainAddress" class="form-control" />
                    <span asp-validation-for="MainAddress" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="State" class="control-label"></label>
                    <input asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Landmark" class="control-label"></label>
                    <input asp-for="Landmark" class="form-control" />
                    <span asp-validation-for="Landmark" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AlternatePhone" class="control-label"></label>
                    <input asp-for="AlternatePhone" class="form-control" />
                    <span asp-validation-for="AlternatePhone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Deliver to this Address" class="btn btn-primary" />
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <h2 class="text-center main-title">Pick Up From Store</h2>
            <div style="border: solid 1px gray; padding: 20px">
                <h3></h3>
                <p>
                    Shop No. 25, BMC Market, Opp. Railway Station, Borivali West
                    Mumbai, Maharashtra - 400092 , India
                </p>


                <a class="btn btn-primary" asp-action="CheckOutOptions" asp-route-productId="@ViewBag.productId" asp-route-qty="@ViewBag.qty"> <span><i class="fas fa-store mr-2"></i></span>Pick Up From Store</a>
                <br />

            </div>
        </div>
    </div>
</div>

CateBase/Views/BuyNow/Payment.cshtml
@{
    ViewData["Title"] = "Payment";
}





    <div class="alus-breadcrumb breadcrumb-layout1" style="background-image:url();">
        <div class="container">
            <div class="breadcrumb-title-inner">
                <h1 class="breadcrumb-title">Payment</h1>
                <div class="breadcrumbs">
                    <div class="breadcrumbs-content">
                        <a asp-controller="Cart" asp-action="Index" title="Cart">Cart</a>
                        <span class="divider">
                            <i class="fas fa-angle-right"></i>
                        </span>
                        <a asp-controller="Checkout" asp-action="Address" title="Cart">Address</a>
                        <span class="divider">
                            <i class="fas fa-angle-right"></i>
                        </span>
                        Payment
                    </div>
                </div>
            </div>
        </div>
    </div>

CateBase/Views/BuyNow/PaymentFailed.cshtml
@{
    ViewData["Title"] = "Payment Failed";
}



    <h1>Payment Failed</h1>
@* <a asp-controller="Home" asp-action="Index" class="button">Continue Shopping</a> *@

<a asp-action="Address" class="button">Retry</a>

CateBase/Views/BuyNow/PaymentOptions.cshtml
@model BasePackageModule1.Controllers.BuyNowController.APaymentOptions
<div class="container">
    <div class="row mt-5 mb-5">
        <div class="col-md-6 offset-md-2">
            <h4>Payment Option</h4> 
            <form class="form" asp-action="PaymentOptions" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>

                <input type="hidden" asp-for="AddressId" />
                <input type="hidden" asp-for="ProductId" />
                <input type="hidden" asp-for="Qty" />
                <div class="form-check mt-2 mb-2">
                    <label class="form-check-label">
                        <input type="radio" value="payOnline" asp-for="PaymentOption" class="form-check-input"> Pay Online
                    </label>
                </div>

                <div class="form-check mt-2 mb-2">
                    <label class="form-check-label">
                        <input type="radio" value="cashOnDelivery" asp-for="PaymentOption" class="form-check-input"> Cash On Delivery
                    </label>
                </div>

                <button type="submit" class=" btn btn-primary btn-block">Confirm Order</button>
            </form>
        </div>
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title text-center text-primary">Order Summary</h5>
                    <hr />
                    <ul class="order-summary">
                        <li>Items:	  <span class="float-right">₹ @ViewBag.Items</span></li>
                        <li> Delivery:<span class="float-right">₹ 00</span></li>
                        <li>Total:	   <span class="float-right">₹ @ViewBag.Items</span></li>
                        <li>Promotion Applied:	-  <span class="float-right">₹ 00</span></li>
                        <hr />
                        <li><h5 class="text-primary">Order Total:<span class="float-right">₹ @ViewBag.Items</span></h5></li>
                    </ul>

                </div>
            </div>

        </div>
    </div>
</div>

CateBase/Views/BuyNow/ThankYou.cshtml
@{
    ViewBag.Title = "Thank you";
}



<h2>Thank you for payment</h2>
<p>Your Order has been placed</p>

<a asp-controller="Home" asp-action="Index" class="button">Continue Shopping</a>

<a asp-action="Index" asp-controller="Orders" class="button">Goto Orders</a>